# from: https://github.com/marketplace/actions/link-checker

name: Link Check on README.md

on: push
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Link Checker
      id: lc
      uses: peter-evans/link-checker@v1
      with:
        args: -v -d . -x "http://creativecommons.org/licenses|https://isc-inviter.herokuapp.com" README.md
    - name: Fail if there were link errors
      run: exit ${{ steps.lc.outputs.exit_code }}
